package converter

import (
	"bytes"
	"io"
	"strings"
	"testing"

	"github.com/handaber/cfg2env/plugin"
)

// mockPlugin implements plugin.Plugin for testing
type mockPlugin struct {
	plugin.BasePlugin
	parseFunc func(io.Reader) (map[string]string, error)
}

func (p *mockPlugin) Parse(r io.Reader) (map[string]string, error) {
	return p.parseFunc(r)
}

// testPlugin implements a simple plugin for testing
type testPlugin struct {
	plugin.BasePlugin
	data map[string]string
}

func (p *testPlugin) Parse(r io.Reader) (map[string]string, error) {
	return p.data, nil
}

func TestConverter_Convert(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    string
		wantErr bool
	}{
		{
			name:  "basic key-value pairs",
			input: "key=value",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value\n",
		},
		{
			name:  "values with spaces",
			input: "key=value with spaces",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value with spaces\n",
		},
		{
			name:  "empty values",
			input: "key=",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=\n",
		},
		{
			name:    "plugin error",
			input:   "error",
			wantErr: true,
		},
		{
			name:  "empty input",
			input: "",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\n",
		},
		{
			name:  "single character values",
			input: "k=v",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nK=v\n",
		},
		{
			name:  "mixed value types",
			input: "str=text\nnum=123\nbool=true",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nBOOL=true\nNUM=123\nSTR=text\n",
		},
		{
			name:  "case sensitivity",
			input: "KEY=VALUE\nkey=value",
			want:  "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create mock plugin
			p := &mockPlugin{
				BasePlugin: plugin.NewBasePlugin("mock"),
				parseFunc: func(r io.Reader) (map[string]string, error) {
					if tt.input == "error" {
						return nil, io.ErrUnexpectedEOF
					}

					// Parse input into map
					env := make(map[string]string)
					for _, line := range strings.Split(tt.input, "\n") {
						if line == "" {
							continue
						}
						parts := strings.SplitN(line, "=", 2)
						if len(parts) == 2 {
							env[parts[0]] = parts[1]
						}
					}
					return env, nil
				},
			}

			// Create converter with mock plugin
			c := New(p)

			// Convert input
			var out bytes.Buffer
			err := c.Convert(strings.NewReader(tt.input), &out)

			// Check error
			if (err != nil) != tt.wantErr {
				t.Errorf("Convert() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if tt.wantErr {
				return
			}

			// Check output
			if got := out.String(); got != tt.want {
				t.Errorf("Convert() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestConverter_Convert_OutputFormatting(t *testing.T) {
	tests := []struct {
		name  string
		input map[string]string
		want  string
	}{
		{
			name: "special characters",
			input: map[string]string{
				"key": "value with spaces",
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value with spaces\n",
		},
		{
			name: "quotes in values",
			input: map[string]string{
				"key": `value with "quotes"`,
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value with \"quotes\"\n",
		},
		{
			name: "multiple special chars",
			input: map[string]string{
				"key": `value with "quotes" and spaces`,
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value with \"quotes\" and spaces\n",
		},
		{
			name: "all special characters",
			input: map[string]string{
				"key": `!@#$%^&*()_+-=[]{}|;:'",.<>?/~` + "`",
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=!@#$%^&*()_+-=[]{}|;:'\",.<>?/~`\n",
		},
		{
			name: "unicode characters",
			input: map[string]string{
				"key": "value with 日本語",
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=value with 日本語\n",
		},
		{
			name: "environment variable syntax",
			input: map[string]string{
				"key": "$HOME/path",
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=$HOME/path\n",
		},
		{
			name: "shell special characters",
			input: map[string]string{
				"key": "$(command)",
			},
			want: "# This file was auto-generated by cfg2env\n# Version: dev\n# Plugin: mock\n#\n\nKEY=$(command)\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create mock plugin
			p := &mockPlugin{
				BasePlugin: plugin.NewBasePlugin("mock"),
				parseFunc: func(r io.Reader) (map[string]string, error) {
					return tt.input, nil
				},
			}

			// Create converter with mock plugin
			c := New(p)

			// Convert input
			var out bytes.Buffer
			err := c.Convert(strings.NewReader(""), &out)
			if err != nil {
				t.Fatalf("Convert() error = %v", err)
			}

			// Check output
			if got := out.String(); got != tt.want {
				t.Errorf("Convert() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestConverter_Convert_InputValidation(t *testing.T) {
	tests := []struct {
		name    string
		input   io.Reader
		output  io.Writer
		wantErr bool
	}{
		{
			name:    "nil input",
			input:   nil,
			output:  &bytes.Buffer{},
			wantErr: true,
		},
		{
			name:    "nil output",
			input:   strings.NewReader(""),
			output:  nil,
			wantErr: true,
		},
		{
			name:    "failing reader",
			input:   &failingReader{},
			output:  &bytes.Buffer{},
			wantErr: true,
		},
		{
			name:    "failing writer",
			input:   strings.NewReader("key=value"),
			output:  &failingWriter{},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create mock plugin
			p := &mockPlugin{
				BasePlugin: plugin.NewBasePlugin("mock"),
				parseFunc: func(r io.Reader) (map[string]string, error) {
					if _, ok := r.(*failingReader); ok {
						return nil, io.ErrUnexpectedEOF
					}
					return map[string]string{"key": "value"}, nil
				},
			}

			// Create converter with mock plugin
			c := New(p)

			// Convert input
			err := c.Convert(tt.input, tt.output)
			if (err != nil) != tt.wantErr {
				t.Errorf("Convert() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

// failingReader always returns an error on Read
type failingReader struct{}

func (r *failingReader) Read(p []byte) (n int, err error) {
	return 0, io.ErrUnexpectedEOF
}

// failingWriter always returns an error on Write
type failingWriter struct{}

func (w *failingWriter) Write(p []byte) (n int, err error) {
	return 0, io.ErrShortWrite
}

func TestConverterHeader(t *testing.T) {
	// Create a simple test plugin
	p := &testPlugin{
		BasePlugin: plugin.NewBasePlugin("test"),
		data: map[string]string{
			"key": "value",
		},
	}

	// Create converter with test version
	c := New(p)
	c.SetVersion("1.0.0-test")

	// Convert
	var buf bytes.Buffer
	if err := c.Convert(strings.NewReader(""), &buf); err != nil {
		t.Fatalf("Convert failed: %v", err)
	}

	// Get output lines
	output := buf.String()
	lines := strings.Split(output, "\n")

	// Check header
	expectedHeaders := []string{
		"# This file was auto-generated by cfg2env",
		"# Version: 1.0.0-test",
		"# Plugin: test",
		"#",
		"",
	}

	if len(lines) < len(expectedHeaders) {
		t.Fatalf("Output too short, got %d lines, want at least %d", len(lines), len(expectedHeaders))
	}

	for i, expected := range expectedHeaders {
		if lines[i] != expected {
			t.Errorf("Header line %d mismatch:\ngot:  %q\nwant: %q", i+1, lines[i], expected)
		}
	}

	// Verify the actual env content is still there
	found := false
	for _, line := range lines {
		if line == "KEY=value" {
			found = true
			break
		}
	}
	if !found {
		t.Error("Environment variable content not found in output")
	}
}
